on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      default-latest-tag:
        type: boolean
        default: true
      additional-latest-tag-name:
        type: string
        default: ''
      unstable-tag-name:
        type: string
        default: unstable
    secrets:
      gh-token:
        required: true
      docker-username:
        required: true
      docker-password:
        required: true

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      # Creates an expression to be used in docker/metadata-action
      - name: Expression for additional latest tag
        id: latest-tag
        run: |
          tagName="${{ inputs.additional-latest-tag-name }}"
          if [[ -n ${tagName} ]]; then
            expression="type=raw,value=${tagName},enable=${{ github.event_name == 'release' }}"
          else
            expression=""
          fi
          echo "expression=${expression}" >> $GITHUB_OUTPUT

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@2c0bd771b40637d97bf205cbccdd294a32112176 # v4.5.0
        with:
          images: |
            ${{ inputs.image-name }}
            ghcr.io/${{ inputs.image-name }}
          flavor: |
            latest=${{ inputs.default-latest-tag == true && 'auto' || 'false' }}
          tags: |
            type=ref,event=tag
            type=ref,event=pr
            # set additional latest tag if available
            ${{ steps.latest-tag.outputs.expression }}
            # set unstable tag for develop branch
            type=raw,value=${{ inputs.unstable-tag-name }},enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}

      # Build Docker image with Buildx
      - name: Build Docker image
        uses: docker/build-push-action@44ea916f6c540f9302d50c2b1e5a8dc071f15cdf # v4.1.0
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # As we use multiple registries, we need to extract the first tag from the meta output
      - name: Extract trivy image-ref
        id: extract
        run: |
          firstTag=$(jq --raw-output '.tags[0]' <<< '${{ steps.meta.outputs.json }}')
          echo "Found $firstTag as first tag"
          echo "imageRef=$firstTag" >> $GITHUB_OUTPUT

      # Scan Docker image (not for release builds since we will have multiple tags)
      - name: Scan Docker image
        if: github.event_name != 'release'
        uses: aquasecurity/trivy-action@41f05d9ecffa2ed3f1580af306000f734b733e54 # 0.11.2
        with:
          image-ref: ${{ steps.extract.outputs.imageRef }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      # Publish scan report to GitHub
      - name: Publish scan report to GitHub
        if: ${{ github.event_name != 'release' && always() }}
        uses: github/codeql-action/upload-sarif@83f0fe6c4988d98a455712a27f0255212bba9bd4 # v2.3.6
        with:
          sarif_file: trivy-results.sarif

      # Create Software Bill of Materials (SBOM) (not for release builds since we will have multiple tags)
      - name: Create Software Bill of Materials (SBOM)
        if: github.event_name == 'push'
        uses: aquasecurity/trivy-action@41f05d9ecffa2ed3f1580af306000f734b733e54 # 0.11.2
        with:
          image-ref: ${{ steps.extract.outputs.imageRef }}
          format: 'github'
          output: 'dependency-results.sbom.json'
          github-pat: ${{ secrets.gh-token }}

      # Login to Docker registry if not PR build
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-password }}

      # Login to GitHub Container Registry if not PR build
      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.gh-token }}

      # Publish Docker image for CI builds if not PR build
      - name: Push container image
        uses: docker/build-push-action@44ea916f6c540f9302d50c2b1e5a8dc071f15cdf # v4.1.0
        if: github.event_name != 'pull_request'
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Update Readme on Docker Hub
      - name: Publish README to Docker Hub
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@579f64ca0abced29dbbc44ab4c6a0b9e33ab3588 # v3.4.1
        with:
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-password }}
          repository: ${{ inputs.image-name }}