on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      default-latest-tag:
        type: boolean
        default: true
      additional-latest-tag-name:
        type: string
        default: ''
      default-unstable-tag:
        type: boolean
        default: true
      additional-unstable-tag-name:
        type: string
        default: ''
      release-tag-suffix:
        type: string
        default: ''
    secrets:
      gh-token:
        required: true
      docker-username:
        required: true
      docker-password:
        required: true

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Creates an expression to be used in docker/metadata-action
      - name: Expressions for additional tags
        id: additional-tags
        run: |
          latestTagName="${{ inputs.additional-latest-tag-name }}"
          if [[ -n ${latestTagName} ]]; then
            latestExpression="type=raw,value=${latestTagName},enable=${{ github.event_name == 'release' }}"
          else
            latestExpression=""
          fi
          unstableTagName="${{ inputs.additional-unstable-tag-name }}"
          if [[ -n ${unstableTagName} ]]; then
            unstableExpression="type=raw,value=${unstableTagName},enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}"
          else
            unstableExpression=""
          fi
          echo "latest-expression=${latestExpression}" >> $GITHUB_OUTPUT
          echo "unstable-expression=${unstableExpression}" >> $GITHUB_OUTPUT

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: |
            ${{ inputs.image-name }}
            ghcr.io/${{ inputs.image-name }}
          flavor: |
            latest=${{ inputs.default-latest-tag == true && 'auto' || 'false' }}
          tags: |
            type=ref,event=tag,suffix=${{ inputs.release-tag-suffix != '' && '-' || '' }}${{ inputs.release-tag-suffix }}
            type=ref,event=pr
            # set additional tags if available
            ${{ steps.additional-tags.outputs.latest-expression }}
            ${{ steps.additional-tags.outputs.unstable-expression }}
            # set default unstable tag for develop branch
            type=raw,value=unstable,enable=${{ inputs.default-unstable-tag == true && github.ref == format('refs/heads/{0}', 'develop') }}

      # Build Docker image with Buildx
      - name: Build Docker image
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # As we use multiple registries, we need to extract the first tag from the meta output
      - name: Extract trivy image-ref
        id: extract
        run: |
          firstTag=$(jq --raw-output '.tags[0]' <<< '${{ steps.meta.outputs.json }}')
          echo "Found $firstTag as first tag"
          echo "imageRef=$firstTag" >> $GITHUB_OUTPUT

      # Scan Docker image (not for release builds since we will have multiple tags)
      - name: Scan Docker image
        if: github.event_name != 'release'
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # 0.29.0
        with:
          image-ref: ${{ steps.extract.outputs.imageRef }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      # Publish scan report to GitHub
      - name: Publish scan report to GitHub
        if: ${{ github.event_name != 'release' && always() }}
        uses: github/codeql-action/upload-sarif@babb554ede22fd5605947329c4d04d8e7a0b8155 # v3.27.7
        with:
          sarif_file: trivy-results.sarif

      # Create Software Bill of Materials (SBOM) (not for release builds since we will have multiple tags)
      - name: Create Software Bill of Materials (SBOM)
        if: github.event_name == 'push'
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # 0.29.0
        with:
          image-ref: ${{ steps.extract.outputs.imageRef }}
          format: 'github'
          output: 'dependency-results.sbom.json'
          github-pat: ${{ secrets.gh-token }}

      # Login to Docker registry if not PR build
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-password }}

      # Login to GitHub Container Registry if not PR build
      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.gh-token }}

      # Publish Docker image for CI builds if not PR build
      - name: Push container image
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        if: github.event_name != 'pull_request'
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Update Readme on Docker Hub
      - name: Publish README to Docker Hub
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae # v4.0.0
        with:
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-password }}
          repository: ${{ inputs.image-name }}