on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      default-latest-tag:
        type: boolean
        default: true
      additional-latest-tag-name:
        type: string
        default: ''
      default-unstable-tag:
        type: boolean
        default: true
      additional-unstable-tag-name:
        type: string
        default: ''
      release-tag-suffix:
        type: string
        default: ''
    secrets:
      gh-token:
        required: true
      docker-username:
        required: true
      docker-password:
        required: true

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # Creates an expression to be used in docker/metadata-action
      - name: Expressions for additional tags
        id: additional-tags
        run: |
          latestTagName="${{ inputs.additional-latest-tag-name }}"
          if [[ -n ${latestTagName} ]]; then
            latestExpression="type=raw,value=${latestTagName},enable=${{ github.event_name == 'release' }}"
          else
            latestExpression=""
          fi
          unstableTagName="${{ inputs.additional-unstable-tag-name }}"
          if [[ -n ${unstableTagName} ]]; then
            unstableExpression="type=raw,value=${unstableTagName},enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}"
          else
            unstableExpression=""
          fi
          echo "latest-expression=${latestExpression}" >> $GITHUB_OUTPUT
          echo "unstable-expression=${unstableExpression}" >> $GITHUB_OUTPUT

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@31cebacef4805868f9ce9a0cb03ee36c32df2ac4 # v5.3.0
        with:
          images: |
            ${{ inputs.image-name }}
            ghcr.io/${{ inputs.image-name }}
          flavor: |
            latest=${{ inputs.default-latest-tag == true && 'auto' || 'false' }}
          tags: |
            type=ref,event=tag,suffix=${{ inputs.release-tag-suffix != '' && '-' || '' }}${{ inputs.release-tag-suffix }}
            type=ref,event=pr
            # set additional tags if available
            ${{ steps.additional-tags.outputs.latest-expression }}
            ${{ steps.additional-tags.outputs.unstable-expression }}
            # set default unstable tag for develop branch
            type=raw,value=unstable,enable=${{ inputs.default-unstable-tag == true && github.ref == format('refs/heads/{0}', 'develop') }}

      # Build Docker image with Buildx
      - name: Build Docker image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # As we use multiple registries, we need to extract the first tag from the meta output
      - name: Extract trivy image-ref
        id: extract
        run: |
          firstTag=$(jq --raw-output '.tags[0]' <<< '${{ steps.meta.outputs.json }}')
          echo "Found $firstTag as first tag"
          echo "imageRef=$firstTag" >> $GITHUB_OUTPUT

      # Scan Docker image (not for release builds since we will have multiple tags)
      - name: Scan Docker image
        if: github.event_name != 'release'
        uses: aquasecurity/trivy-action@91713af97dc80187565512baba96e4364e983601 # 0.16.0
        with:
          image-ref: ${{ steps.extract.outputs.imageRef }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      # Publish scan report to GitHub
      - name: Publish scan report to GitHub
        if: ${{ github.event_name != 'release' && always() }}
        uses: github/codeql-action/upload-sarif@b374143c1149a9115d881581d29b8390bbcbb59c # v3.22.11
        with:
          sarif_file: trivy-results.sarif

      # Create Software Bill of Materials (SBOM) (not for release builds since we will have multiple tags)
      - name: Create Software Bill of Materials (SBOM)
        if: github.event_name == 'push'
        uses: aquasecurity/trivy-action@91713af97dc80187565512baba96e4364e983601 # 0.16.0
        with:
          image-ref: ${{ steps.extract.outputs.imageRef }}
          format: 'github'
          output: 'dependency-results.sbom.json'
          github-pat: ${{ secrets.gh-token }}

      # Login to Docker registry if not PR build
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-password }}

      # Login to GitHub Container Registry if not PR build
      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.gh-token }}

      # Publish Docker image for CI builds if not PR build
      - name: Push container image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        if: github.event_name != 'pull_request'
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Update Readme on Docker Hub
      - name: Publish README to Docker Hub
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@dc67fad7001ef9e8e3c124cb7a64e16d0a63d864 # v3.4.2
        with:
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-password }}
          repository: ${{ inputs.image-name }}